[supabase]
url = "https://begfenyzftqeucnahmmu.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZ2Zlbnl6ZnRxZXVjbmFobW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NDEzMTgsImV4cCI6MjA3NjMxNzMxOH0.R0MlrMhlQ_2XESd2cxnmcQAO6Ga5G8nC4wMsTrJx-38"

[app]
force_readonly = false

[theme]  # ← dit is de app-thema sectie die mijn code leest
bg = "#8DAEBA"
surface = "#99883F"
card = "#A38B16"
border = "#2a355a"
text = "#11064D"            # ← 1 hekje
muted = "#9fb0d9"
primary = "#728DCC"
primary_contrast = "#453A06"
accent = "#22d3ee"
success = "#3CA133"
warning = "#f59e0b"
error = "#ef4444"
